apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer
  name: customer
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  strategy: {}
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: 019050461780.dkr.ecr.eu-west-1.amazonaws.com/abdelatif-ecr-customer:a5476fd5bb073993d7b2c5caec073c5aad17c624
        name: customer
        ports:
        - containerPort: 7070

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
  name: customer-service
  namespace: blue
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: customer
  type: ClusterIP
status: