apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
  name: product
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: 019050461780.dkr.ecr.eu-west-1.amazonaws.com/abdelatif-ecr-product:44c5ea1a526f7c6a95efb089425e983940c0190a
        name: product
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-service
  namespace: blue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product
  type: ClusterIP
status: