apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: canari
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: automatically
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
