apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-green
  namespace: green
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ubuntu/WordPress

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-green
  namespace: green
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual