apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: ingress
  namespace: green
  annotations:
    #cert-manager.io/issuer: letsencrypt-issuer-wordpress
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/custom-http-errors: '404'
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900200,phase:1,nolog,pass,t:none,\
        setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"

#SecRuleRemoveById 911100
spec:
# tls:
# - hosts:
#projetc.abdelatif-aitbara.link
#   secretName: projetc.abdelatif-aitbara.link
  ingressClassName: nginx
  rules:
  - host: projetc.abdelatif-aitbara.link	
    http:  
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: wordpress-service
            port:  
              number: 80
      - path: /customer
        pathType: Prefix
        backend:    
          service:
            name: customer-service 
            port:
              number: 7070
      - path: /product
        pathType: Prefix
        backend:    
          service:
            name: product-service 
            port:
              number: 8080
      - path: /order
        pathType: Prefix
        backend:    
          service:
            name: order-service 
            port:
              number: 9090