apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: wordpress
  name: wordpress
spec:
  maxReplicas: 7
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
    subresouce: scale
  targetCPUUtilizationPercentage: 50