apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployment
  namespace: wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: wordpress
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90