apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec: 
  rules:
    - http: 
        paths:
          - path: /wordpress
            backend:     
              serviceName: wordpress-service
              servicePort: 80
  ingressClassName: nginx