apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: wordpress
spec:
  rules:
  - host: abdelatif-alb-1282074344.eu-west-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
  ingressClassName: nginx

