apiVersion: networking.k8s.io/v1   
kind: Ingress
metadata:
  name: ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:  
  rules:
  - http:
      paths:
      - path: /microservice-product/(add_product|delete_product|get_product/?|update_product)
        pathType: Prefix 
        backend:  
          service:
            name: product-service
            port:   
              number: 8080
  ingressClassName: nginx