apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  rules:
    - http:
        paths:
          - path: /add_product
            pathType: Prefix
            backend: 
              service:
                name: product-service
                port:    
                  number: 8080
          - path: /delete_product
            pathType: Prefix 
            backend:   
              service:
                name: product-service
                port:     
                  number: 8080  
          - path: /get_product
            pathType: Prefix  
            backend:    
              service:
                name: product-service
                port:     
                  number: 8080
          - path: /update_product 
            pathType: Prefix
            backend:   
              service: 
                name: product-service
                port:     
                  number: 8080
  ingressClassName: nginx