apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress 
  namespace: wordpress
spec:
  ingressClassName: nginx
  rules:
  - host: abdelatif-alb-1033670968.eu-west-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service: 
            name: wordpress
            port:
              number: 80