apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: abdelatif-alb-1033670968.eu-west-1.elb.amazonaws.com
    http:
      paths:
      - path: /wordpress
        backend:
          serviceName: wordpress-service
          servicePort: 80
  ingressClassName: nginx