apiVersion: nnetworking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress
  namespace: wordpress
spec:
  rules:
  - host: abdelatif-alb-1033670968.eu-west-1.elb.amazonaws.com
    http:
      paths:
      - backend:
          serviceName: wordpress-service
          servicePort: 80
        path: /devops(/|$)(.*)