apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: ingress
  namespace: wordpress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/auth-tls-secret: "wordpress/wp-app-tls"
spec:
  ingressClassName: nginx
  rules:
  - host: wp.abdelatif-aitbara.link	
    http:  
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: wordpress-service
            port:  
              number: 80
      - path: /customer
        pathType: Prefix
        backend:    
          service:
            name: customer-service 
            port:
              number: 7070
      - path: /product
        pathType: Prefix
        backend:    
          service:
            name: product-service 
            port:
              number: 8080
      - path: /order
        pathType: Prefix
        backend:    
          service:
            name: order-service 
            port:
              number: 9090