apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: NUFvOVNqclU5NmZwSwo=
  mysql-root-password: abcd1234567
  mysql-user: robin
  mysql-password: abcd1234567
  mysql-database: wordpress
