apiVersion: v1
kind: ConfigMap 
metadata:
  name: mysql-config
  namespace: wordpress
data:
  inidb.sql: |
    CREATE DATABASE wordpress;
    CREATE USER 'wordpress'@'%' IDENTIFIED BY 'password'; 
    GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';
    FLUSH PRIVILEGES;