apiVersion: v1
kind: ConfigMap 
metadata:
  name: mysql-config
data:
  init.sh: |
    #!/bin/sh
    echo "Initializing MySQL..."
    CREATE USER 'first_user'@'%' IDENTIFIED BY '111' ;
    CREATE USER 'second_user'@'%' IDENTIFIED BY '222' ;