apiVersion: v1
kind: ConfigMap 
metadata:
  name: mysql-config
  namespace: wordpress
data:
  inidb.sql: |
    CREATE USER 'new_user'@'localhost' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON *.* TO 'new_user'@'localhost';
    FLUSH PRIVILEGES;