apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
data:
  wp-config.php: |
    // (See also https://wordpress.stackexchange.com/a/152905/199287)
    /**#@-*/

    /**
    * WordPress database table prefix.
    *
    * You can have multiple installations in one database if you give each
    * a unique prefix. Only numbers, letters, and underscores please!
    */
    $table_prefix = getenv_docker('WORDPRESS_TABLE_PREFIX', 'wp_');

    /**
    * For developers: WordPress debugging mode.
    *
    * Change this to true to enable the display of notices during development.
    * It is strongly recommended that plugin and theme developers use WP_DEBUG
    * in their development environments.
    *
    * For information on other constants that can be used for debugging,
    * visit the documentation.
    *
    * @link https://wordpress.org/documentation/article/debugging-in-wordpress/
    */
    define( 'WP_DEBUG', !!getenv_docker('WORDPRESS_DEBUG', '') );

    /* Add any custom values between this line and the "stop editing" line. */

    // If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
    // see also https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
            $_SERVER['HTTPS'] = 'on';
    }
    // (we include this by default because reverse proxying is extremely common in container environments)

    if ($configExtra = getenv_docker('WORDPRESS_CONFIG_EXTRA', '')) {
            eval($configExtra);
    }

    /* That's all, stop editing! Happy publishing. */

    /** Absolute path to the WordPress directory. */
    if ( ! defined( 'ABSPATH' ) ) {
            define( 'ABSPATH', __DIR__ . '/' );
    }

    /** Sets up WordPress vars and included files. */
    require_once ABSPATH . 'wp-settings.php';





    define('WP_HOME','http://projetc.abdelatif-aitbara.link/');
    define('WP_SITEURL','http://projetc.abdelatif-aitbara.link/');


    /* That's all, stop editing! Happy publishing. */