apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-blue
  namespace: blue
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-blue
  namespace: blue
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi