apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-blue
  namespace: blue
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: gp3
    volumeID: aws://eu-west-1a/vol-05328650f74f2254e


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-blue
  namespace: blue
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  