# CSIPersistentVolume
apiVersion: csi.storage.k8s.io/v1
kind: CSIPersistentVolume
metadata:
  name: wordpress-pv-blue
spec:
  capacity:
    storage: 10Gi 
  csi: 
    driver: ebs.csi.aws.com
    volumeHandle: vol-05328650f74f2254e
    volumeAttributes:
      zone: eu-west-1a
      

# PersistentVolumeClaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-blue
  namespace: blue
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: wordpress-pv