---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-blue
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 1000m  
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service-blue
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-blue
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_NAME
              value: wordpress
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc-blue
---

kind: Service
apiVersion: v1
metadata:
  name: wordpress-service-blue
  namespace: blue
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80

