---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-blue
  namespace: blue
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: gp3
    volumeID: aws://eu-west-1a/vol-05328650f74f2254e
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wordpress
  name: wordpress-pvc-blue
  namespace: blue
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp3-retain
  volumeMode: Filesystem
  volumeName: wordpress-pvc-blue