apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
  name: order
  namespace: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  strategy: {}
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: 019050461780.dkr.ecr.eu-west-1.amazonaws.com/abdelatif-ecr-order:2b34f086687f34aebb56afc546244d7d8c24f74c
        name: order
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order-service
  namespace: green
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: order
  type: ClusterIP
status: