apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer
  name: customer
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  strategy: {}
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - image: abdelatifaitbara/customer:${GIT_COMMIT}
        name: customer
        ports:
        - containerPort: 7070
        resources: {}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer
  name: customer-service
  namespace: wordpress
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: customer
  type: ClusterIP
status: