apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
  name: order
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  strategy: {}
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: abdelatifaitbara/order:e4a227bc3df2bcf4921a2ed5ad958dc74042983f
        name: order
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order-service
  namespace: wordpress
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: order
  type: ClusterIP
status: