apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
  name: order
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  strategy: {}
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: 019050461780.dkr.ecr.eu-west-1.amazonaws.com/abdelatif-ecr-order:8f6b0467b88f791833507c644fb4d558c5f57063
        name: order
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order-service
  namespace: wordpress
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: order
  type: ClusterIP
status: