apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
  name: product
  namespace: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: abdelatifaitbara/product:779c3143a7203453e566e40df0ed9075d98db080
        name: product
        ports:
        - containerPort: 8080
        resources: {}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-service
  namespace: wordpress
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product
  type: ClusterIP
status: