apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
  name: product
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  strategy: {}
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - image: abdelatifaitbara/product:v1.0.1
        name: product
        ports:
        - containerPort: 8080
        resources: {}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product-service
  namespace: wordpress
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product
  type: ClusterIP
status: