apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret 
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |-
    {
      "auths": {
        "019050461780.dkr.ecr.eu-west-1.amazonaws.com": {
          "username": "AWS",
          "auth": "YWJkZWxhdGlmYWl0YmFyYTpkY2tyX3BhdF9pQlhfODY1TDBjV29QaTB0N3ZXRVQ5SXNkUVE="
        }
      }
    }