apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer-wordpress
  namespace: green
spec:
  acme:
    email: aait-bara@thenuumfactory.fr
    privateKeySecretRef:
      name: lets-encrypt-secret-issuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx